Repository Jonathan204/SyncStream, pull requests merged in 2021-04, with the labels that each got.

#144 141 fix spotify first time bug
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Player/Player.js
Labels: 1 point, Frontend, Medium Priority, Medium Risk, bug

#145 Fixing some code inconsistencies
  client/src/App.js
  client/src/components/Map/InfoWindow/InfoWindow.js
  client/src/components/Map/InfoWindow/styles.css
  client/src/components/Map/Map.js
  client/src/components/Map/MarkerLocation/MarkerLocation.js
  client/src/components/Map/Tests/Map.test.js
  client/src/components/Map/mapStyles.js
  client/src/components/Player/Player.js
  client/src/components/Profile/Profile.js
  client/src/index.js
Labels: 1 point, Low Priority, Low Risk

#147 Added profile pictures for linked accounts
  client/src/components/Map/Map.js
  client/src/components/Map/MarkerLocation/MarkerLocation.js
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/Profile/Profile.js
  server/controllers/users.js
  server/models/userSchema.js
Labels: 1 point, Frontend, Low Priority, Low Risk

#150 148 general styling
  client/public/index.html
  client/public/styles.css
  client/src/components/Account/Login.js
  client/src/components/Account/Register.js
  client/src/components/Account/styles.css
  client/src/components/Map/InfoWindow/InfoWindow.js
  client/src/components/Map/InfoWindow/styles.css
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/NavigationBar/styles.css
  client/src/components/Player/Player.js
  client/src/components/Player/styles.css
  client/src/components/Profile/Profile.js
  client/src/components/Profile/styles.css
  client/src/images/logoWhite.png
Labels: 1 point, Frontend, Low Priority, Low Risk

#151 149 more validation tests
  client/src/components/Account/Tests/validation.test.js
  client/src/components/Account/validation.js
Labels: 1 point, Frontend, Low Priority, Low Risk, Test

#152 Prepare deploy
  client/.env.example
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/api/index.js
  client/src/components/Map/Map.js
  client/src/components/Profile/Profile.js
  package.json
  server/index.js
  server/package.json
  server/test/unit/userSchema.test.js
Labels: 1 point, Low Priority, Medium Risk, enhancement

#154 Updated Cypress Tests
  client/cypress/integration/Account_spec.js
Labels: 1 point, Low Priority, Low Risk, Test
