Repository Jonathan204/SyncStream, pull requests merged in 2021-02, with the labels that each got.

#34 Create the basic structure of the MERN stack
  .gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/actions/posts.js
  client/src/api/index.js
  client/src/components/Form/Form.js
  client/src/components/Form/styles.js
  client/src/components/Posts/Post/Post.js
  client/src/components/Posts/Post/styles.js
  client/src/components/Posts/Posts.js
  client/src/components/Posts/styles.js
  client/src/constants/actionTypes.js
  client/src/images/logo.png
  client/src/index.js
  client/src/reducers/index.js
  client/src/reducers/posts.js
  client/src/styles.js
  client/yarn.lock
  package-lock.json
  server/controllers/posts.js
  server/index.js
  server/models/postMessage.js
  server/package-lock.json
  server/package.json
  server/routes/posts.js
Labels: Backend, Database, Frontend, High Priority

#36 Added a google map
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Map/Map.js
  client/src/components/Map/styles.js
Labels: Frontend, Medium Priority

#55 Added Navigation Bar
  client/src/App.js
  client/src/components/NavigationBar/NavigationBar.js
  client/src/images/default_account.png
Labels: Frontend

#53 Add user current location
  client/package-lock.json
  client/package.json
  client/src/components/Map/Map.js
  client/src/components/Map/markers/currLocation.js
  client/src/components/Map/markers/currLocationStyle.js
Labels: Frontend, Medium Priority

#56 Create account-backend
  server/controllers/users.js
  server/index.js
  server/models/userSchema.js
  server/package-lock.json
  server/package.json
  server/utils/userUtils.js
Labels: Backend, Database

#58 50-Login-backend
  server/controllers/users.js
  server/routes/users.js
  server/utils/userUtils.js
Labels: Backend

#63 Removed default tempate
  client/src/App.js
Labels: Frontend, Low Priority

#59 Infobox on click
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/markers/currLocation.js
Labels: Frontend

#57 Add login page
  client/package-lock.json
  client/package.json
  client/src/components/Account/Account.js
  client/src/components/Account/AccountContext.js
  client/src/components/Account/Login.js
  client/src/components/Account/Register.js
  client/src/components/Account/styles.css
  client/src/components/NavigationBar/NavigationBar.js
  client/src/index.js
Labels: Frontend

#68 changed to style file instead of inline css
  client/src/components/Account/Account.js
  client/src/components/Account/Login.js
  client/src/components/Account/Register.js
  client/src/components/Account/styles.css
Labels: Frontend

#70 Display what your listening to on the map
  client/package-lock.json
  client/package.json
  client/src/components/Map/infoWindow/config.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/infoWindow/hash.js
  client/src/components/Map/infoWindow/styles.css
  client/src/components/Player/Player.css
  client/src/components/Player/Player.js
  client/src/images/spotify-logo.png
  package-lock.json
Labels: Frontend, High Priority

#69 65 connect backend
  client/src/App.js
  client/src/actions/account.js
  client/src/actions/posts.js
  client/src/actions/users.js
  client/src/api/index.js
  client/src/components/Account/Login.js
  client/src/components/Account/Register.js
  client/src/constants/actionTypes.js
  client/src/reducers/account.js
  client/src/reducers/index.js
  client/src/reducers/posts.js
  client/src/reducers/users.js
Labels: Frontend

#74 Add loading in login and signup
  client/src/actions/account.js
  client/src/components/Account/Login.js
  client/src/components/Account/Register.js
  client/src/constants/actionTypes.js
  client/src/reducers/account.js
Labels: Frontend

#77 75 Error Checking
  client/src/components/Account/Login.js
  client/src/components/Account/Register.js
  client/src/components/Account/validation.js
  client/src/components/Button/LoadingButton.js
  client/src/reducers/account.js
  client/src/reducers/users.js
Labels: Frontend

#79 Link Project to CI Github Actions
  .github/workflows/node.js.yml
  client/jest.config.json
  client/package.json
  client/src/components/Account/Tests/Account.test.js
Labels: Test

#78 Setup user profile page
  client/src/App.js
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/NavigationBar/styles.css
  client/src/components/Profile/Profile.js
  client/src/components/Profile/styles.css
  client/src/index.js
Labels: Frontend

#82 Add spotify id to user account in database
  client/src/actions/account.js
  client/src/api/index.js
  client/src/components/Account/Login.js
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Player/Player.js
  client/src/hash.js
  server/controllers/users.js
Labels: Backend, Frontend, Medium Priority

#83 Linked Profile Page to Backend
  client/src/actions/users.js
  client/src/api/index.js
  client/src/components/Account/styles.css
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/Profile/Profile.js
  client/src/constants/actionTypes.js
  client/src/reducers/account.js
  server/controllers/users.js
Labels: Backend

#87 Add spotify Username to profile page
  client/src/components/Profile/Profile.js
Labels: Frontend, Low Priority

#93 Map loads properly depending on location settings
  client/src/components/Map/Map.js
Labels: Frontend, bug

#92 38 setup user profile page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/actions/account.js
  client/src/components/Map/Map.js
  client/src/components/Profile/Profile.js
  client/src/components/Profile/styles.css
  client/src/constants/actionTypes.js
  client/src/index.js
  client/src/reducers/account.js
Labels: Frontend

#95 94 Update GetUser
  server/controllers/users.js
Labels: Backend, Medium Priority
