Repository Jonathan204/SyncStream, pull requests merged in 2021-03, with the labels that each got.

#101 Make getUsers to only return info needed
  server/controllers/users.js
Labels: Backend, Medium Priority

#102 61 add login test backend
  .github/workflows/node.js.yml
  server/babel.config.cjs
  server/index.js
  server/jest.config.json
  server/package-lock.json
  server/package.json
  server/test/integration/user.test.js
  server/test/unit/userSchema.test.js
Labels: Backend, Medium Priority, Medium Risk, Test

#107 Add users coords to backend
  client/src/components/Map/Map.js
  server/controllers/users.js
  server/models/userSchema.js
Labels: 1 point, Backend, Database, Low Risk, Medium Priority

#109 103 account unit tests
  client/package-lock.json
  client/package.json
  client/src/components/Account/Account.js
  client/src/components/Account/Register.js
  client/src/components/Account/Tests/Account.test.js
  client/src/setupTests.js
Labels: 1 point, Frontend, Low Risk, Medium Priority, Test

#108 62 add create account test backend
  client/src/reducers/account.js
  server/controllers/users.js
  server/test/integration/user.test.js
Labels: 1 point, Backend, Low Risk, Medium Priority, Test

#112 111 fix spotify access bug
  client/.env.example
  client/src/actions/account.js
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/config.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Profile/Profile.js
  client/src/components/Profile/Tests/Profile.test.js
  client/src/hash.js
  server/.env.example
  server/controllers/users.js
  server/models/userSchema.js
  server/package-lock.json
  server/package.json
  server/utils/spotifyUtils.js
Labels: 1 point, Backend, Frontend, Medium Priority, Medium Risk, bug

#116 115 Update user with song info
  client/package.json
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/infoWindow/styles.css
  client/src/components/Map/markers/currLocation.js
  client/src/utils/config.js
  client/src/utils/spotifyUtils.js
  server/controllers/users.js
  server/models/userSchema.js
Labels: 1 point, Backend, Frontend, Medium Priority, Medium Risk

#119 Add getUserSpotify function and route
  server/controllers/users.js
  server/routes/users.js
  server/test/integration/user.test.js
Labels: 1 point, Backend, Low Risk, Medium Priority

#120 Display other users
  client/src/components/Map/Map.js
  client/src/components/Map/markers/currLocation.js
  client/src/components/Map/markers/markerLocation.js
  client/src/reducers/account.js
Labels: 1 point, Frontend, Low Priority, Low Risk

#122 121-update-location-bug
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/markers/markerLocation.js
Labels: 1 point, Frontend, Medium Priority, Medium Risk, bug

#127 41 add login page
  client/src/components/Account/Register.js
Labels: 1 point, Frontend, Low Risk, Medium Priority, bug

#126 114 login styling
  client/public/index.html
  client/public/logo.png
  client/public/styles.css
  client/src/components/Account/Login.js
  client/src/components/Account/Register.js
  client/src/components/Account/styles.css
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/infoWindow/styles.css
  client/src/components/Map/mapStyles.js
  client/src/components/Map/markers/markerLocation.js
  client/src/components/Profile/Profile.js
  client/src/components/Profile/styles.css
Labels: 1 point, Frontend, Low Priority

#129 Click other users
  client/package-lock.json
  client/src/actions/users.js
  client/src/api/index.js
  client/src/components/Map/Map.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/markers/markerLocation.js
  client/src/components/Player/Player.js
  client/src/components/Player/styles.css
  client/src/constants/actionTypes.js
  client/src/reducers/users.js
Labels: 2 Points, Frontend, Low Priority, Low Risk, User story

#132 131 Fix new user not showing up on map
  client/src/components/Map/Map.js
  client/src/reducers/users.js
Labels: 1 point, Frontend, bug

#133 Listen in option
  client/package-lock.json
  client/package.json
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/infoWindow/styles.css
  client/src/components/Player/Player.js
  client/src/components/Player/styles.css
  client/src/utils/config.js
Labels: 1 point, Frontend, High Priority, High risk, User story

#134 117 refresh expired token
  client/src/actions/account.js
  client/src/api/index.js
  client/src/components/Map/infoWindow/currLocation.js
  client/src/components/Map/infoWindow/styles.css
  client/src/components/Map/markers/markerLocation.js
  client/src/components/Player/Player.js
  client/src/constants/actionTypes.js
  client/src/reducers/account.js
  server/controllers/users.js
  server/routes/users.js
Labels: 1 point, Backend, Frontend, bug

#137 Added Cypress and Acceptance Tests
  client/cypress.json
  client/cypress/fixtures/example.json
  client/cypress/integration/Account_spec.js
  client/cypress/plugins/index.js
  client/cypress/support/commands.js
  client/cypress/support/index.js
  client/package-lock.json
  client/package.json
  client/src/components/Account/Register.js
  client/src/components/Map/Map.js
  client/src/components/Map/markers/markerLocation.js
Labels: 1 point, Frontend, Test

#140 Add other user acceptance tests
  client/cypress/integration/Account_spec.js
  client/src/components/Player/Tests/Player.test.js
Labels: 1 point, Low Priority, Low Risk, Test
